# Generated by Django 3.2.20 on 2023-08-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0003_docinfo_wordt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wordt',
        ),
    ]
