# Generated by Django 3.2.20 on 2023-08-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_delete_wordt'),
    ]

    operations = [
        migrations.AddField(
            model_name='docinfo',
            name='frequency',
            field=models.CharField(default=5, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docinfo',
            name='doc_path',
            field=models.CharField(max_length=30),
        ),
    ]
