# Generated by Django 3.2.20 on 2023-08-24 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0005_auto_20230816_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvertedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.ManyToManyField(to='Form.Document')),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Docinfo',
        ),
        migrations.AddField(
            model_name='invertedindex',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Form.word'),
        ),
    ]
