# Generated by Django 3.2.20 on 2023-08-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0006_auto_20230824_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invertedindex',
            name='term',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
